version: "3.8"
services:
  genai_scenarios_ai_target:
    stdin_open: true
    tty: true
    #user: root # Run container as root
    ports:
      - 10004:8888
    volumes:
      - .:/home/jovyan/work
    image: erdemozgen/rar-target-four
networks: {}
