services:
  redairange:
    image: erdemozgen/redairange:1
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      #- 5001:5001
      - 5002:5002

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
        
      # If you want to use private registries, you need to share the auth file with redairange:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      # macOs use full path like /Users/erdem/stacks 
      #- /Users/erdem/Desktop/blackhat/RedAiRange/opt/stacks:/Users/erdem/Desktop/blackhat/RedAiRange/opt/stacks
      - ./opt/stacks:/opt/stacks
    environment:
      # Tell redairange where is your stacks directory
      #- REDAIRANGE_STACKS_DIR=/Users/erdem/Desktop/blackhat/RedAiRange/opt/stacks
      - REDAIRANGE_STACKS_DIR=/opt/stacks
      - REDAIRANGE_PORT=5002
