version: "3.8"
services:
  pytorch-notebook:
    stdin_open: true
    tty: true
    #user: root # Run container as root
    ports:
      - 10101:8888
    volumes:
      - .:/home/jovyan/work
    image: quay.io/jupyter/pytorch-notebook:latest
networks: {}
