  version: '3'

  services:
    pypiserver:
      image: private_pypiserver
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ${PWD}/packages:/data/packages
      networks:
        - backend

    nginx:
      image: nginx:alpine
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ../ssl:/etc/nginx/ssl
      ports:
        - "443:8443"
        - "80:80"
      networks:
        - backend

  networks:
    backend:
