version: "3.8"
services:
  tensorflow-notebook:
    stdin_open: true
    tty: true
    #user: root # Run container as root
    ports:
      - 10102:8888
    volumes:
      - .:/home/jovyan/work
    image: quay.io/jupyter/tensorflow-notebook:latest
networks: {}
