version: "3.8"
services:
  mlsecops_ai_target:
    stdin_open: true
    tty: true
    #user: root # Run container as root
    ports:
      - 11013:8888
    volumes:
      - .:/home/jovyan/work
    image: erdemozgen/rar-target-five
  jenkins-mlsecops:
    build:
      context: ./mlsecops_ai_target/jenkins
    image: jenkins-mlsecops

    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/yanni/models:/downloads/models
      - /home/yanni/scripts/:/scripts
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000

  mlflow-server:
    build:
      context: ./mlsecops_ai_target/mlflow
    image: mlflow-mlsecops
    ports:
      - "5000:5000"
volumes:
  jenkins_home:
  
networks: {}
